### ISSUE TITLE
Generally unclear

### ISSUE THREAD

**Issue by aenbar** [learn-co-curriculum/simple-blackjack-cli#12]
Relying on the tests/errors for this lab doesn't work very well. I love the idea behind it and the overall structure, but I think there should be a little bit more clarity as to what to do for some of the methods- either in the readme or in the blackjack.rb file.

Happy to discuss in person if helpful.

**Comment by SophieDeBenedetto** [comment]
Hey Adam, 

We recently re-organized the methods/tests on this lab to make them more readable but not sure if you're looking at older version or the most up-to-date version. In any case, let me know if you have a few minutes to chat. The idea behind this lab is that the students are reading and struggling to understand error messages on their own after many labs that hold their hands through it, so I feel we should leave more or less as is.

**Comment by AnnJohn** [comment]
Closing issue
