### ISSUE TITLE
Awful lab

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/simple-blackjack-cli#49]
This is a god awful lab and I have been stuck on the #hit? method for weeks.

I'm the kind of person that CANNOT move on with something like the Learn.co curriculum, for example, until I complete tasks in succession. I do not feel as if I am the only person who feels this need and waiting in question-asking limbo is worse than getting the same errors over and over again.

edit: -Including actual suggestion- 

Provide a resource like a search-able forum that individuals can refer to separate from the 2 week limit on similar questions. A static reference with dialogue between someone experiencing a similar problem and an expert is extremely helpful instead of a finite one.

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
