### ISSUE TITLE
THE #INITIAL_ROUND METHOD

### ISSUE THREAD

**Issue by WinnieLee** [learn-co-curriculum/simple-blackjack-cli#64]
THE #INITIAL_ROUND METHOD
This method represents the first round of the game for a given player. It should call on the #deal_card method twice, use the #display_card_total method to puts out the sum and then return the sum. This method will therefore call on two other helper methods, #deal_card and #display_card_total, which takes in an argument of the sum of both invocations of #deal_card.
- Was this method supposed to call on the #deal_card method twice and #display_card_total method once only?
- In another word, is this sentence ("This method will therefore call on two other helper methods, #deal_card and #display_card_total, which takes in an argument of the sum of both invocations of #deal_card.") redundant?

**Comment by pletcher** [comment]
Thanks for opening this issue! Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
