### ISSUE TITLE
can't get the final test of hit? to pass

### ISSUE THREAD

**Issue by Shadow073180** [learn-co-curriculum/simple-blackjack-cli#69]
I can't get the "if user_input = 'h' deal card to pass, it keeps showing the total of the first card.

`require 'pry'

def welcome
 puts ("Welcome to the Blackjack Table")
end

def deal_card
  total = 0
  total += rand(1..11)
end

def display_card_total(sum)
  puts ("Your cards add up to #{sum}")
end
 

def prompt_user
  puts ("Type 'h' to hit or 's' to stay")
end
 

def get_user_input
input = gets.chomp
return input
  
end

def end_game(total)
  puts ("Sorry, you hit #{total}. Thanks for playing!")
end

def initial_round
  sum = deal_card
  sum = sum + deal_card
  display_card_total(sum)
  return sum
end

def hit?(total)
  prompt_user 
  get_user_input
  return total
  
  
end

def invalid_command
  # code invalid_command here
end

#####################################################
# get every test to pass before coding runner below #
#####################################################

def runner
end
`

**Comment by maxwellbenton** [comment]
Hello @Shadow073180,

As per the readme, some logic is involved in the `hit?` method to handle what the user inputs, which is why your solution is not passing. Closing this as it is not an issue related to the functionality of this lab.
